### ISSUE TITLE
Preparing for pilot: hardening core for stability of V1.0

### ISSUE THREAD

**Issue by 0xc0000007b** [inblockio/DataAccounting#157]
Items for 1.0 hardening

Roll-up issue corresponding to task on the project board of the same name:
https://github.com/inblockio/DataAccounting/projects/2#card-72943597

Based on initial review of the DataAccounting codebase the following items should be considered and prioritized. This list is non-exhaustive and a work in progress. It should be broken down into actionable pieces once discussed internally.

Special considerations for pilot

- Smooth backup/restore process to increase user confidence
- MediaWiki "Just Works" (including media uploads with hashing)
- Add extension to the Chrome Web Store (with automatic or easy updates)
- Breaking changes causing users to have to manually update (or very easy container update via script)
- Changes in MW and/or DA extension causing issues
- Breaking changes caused by API changes

In Scope

- [ ] backups #180
  - [ ] Add version number to backup script
  - [ ] Warn when restoring between enviornments
  - [ ] add scheduled backups See related issue in micro-PKC https://github.com/inblockio/micro-PKC/issues/88
  - [ ] fix naming conventsion See related issue in PKC for changing naming convention https://github.com/inblockio/micro-PKC/issues/89
  - [ ] https://github.com/inblockio/micro-PKC/issues/38 (will be obsolete by https://github.com/inblockio/micro-PKC/issues/89)
  - [ ] Related: https://github.com/inblockio/micro-PKC/issues/45
  - [ ] Related: https://github.com/inblockio/micro-PKC/issues/46
  - [ ] Related: https://github.com/inblockio/micro-PKC/issues/49
  - [ ] Related: https://github.com/inblockio/micro-PKC/issues/86
  - [ ] Related: #139 opened 15 days ago by FantasticoFox
  - [ ] https://github.com/inblockio/DataAccounting/issues/158
- [ ] Secure hard-coded database authentication details in build manifest
 - [ ] https://github.com/inblockio/micro-PKC/issues/4
- [x] Own vendored code. WikiMedia back-up script should be forked internally or transferred.
  - [x] https://github.com/inblockio/micro-PKC/issues/76
    - [x] xlp0/mariadb | https://github.com/xlp0/DockerizedMariaDB
    - [x] fantasticofox/pkc | https://github.com/inblockio/mw-docker | https://github.com/inblockio/docker-aqua-mediawiki
    - [x] pelith/node-eauth-server | https://github.com/inblockio/node-eauth-server
- [x] Isolate environments. Create clear boundaries between development and production.
  - [x] https://github.com/inblockio/micro-PKC/issues/65
  - [x] https://github.com/inblockio/micro-PKC/issues/71
- [ ] Repeatable builds. Fully automated and documented in code.
  - [x] Add shell format linter https://github.com/inblockio/micro-PKC/pull/75
  - [x] Standardize scripts dirs CLOSED: Standardize on `scripts` and refactor as we go.
  - [ ] https://github.com/inblockio/docker-aqua-mediawiki/issues/2
- [ ] Reduce dependencies. Eliminate moving parts and reduce size of codebase.
  - [x] https://github.com/inblockio/micro-PKC/issues/63 nice to have
  - [x] Remove parent container wrapping MariaDB (with an attempt at cron) from PKC and build on db images directly
- [x] Add ability to Measure Test Coverage
  - [x] At least partial integration completed as shown here: https://github.com/inblockio/DataAccounting/pull/173
  - [x] Add CodeCov to DataAccounting
  - [ ] Review other repos and integrate CodeCov (and add where it brings most value only)
- [ ] Increase unit test coverage of: DB Access (schema), Function (dependencies), API surface
  - [ ] Review current CodeCov levels and set expectations and targets (as a team).
- [ ] Scan docker containers (automated) and upstream Node deps. Update deps and Node version in Eauth plugin. Surface vulnerable code in CI.
- [ ] Decouple applications. Each can run on its own with a test harness). Each should run their own CI tests independently.
- [ ] Automatically generate change logs
  - [x] Adopt semantic versioning within Core
  - [ ] Choose initial version numbers (start with `0.1.0` or `1.0.0-alphaN`)

# Out of scope for 1.0

- [ ] Investigate ability to run a smoke test as part of CI
   - [ ] Review WebDriver and CLI wallets (https://pkc.inblock.io/index.php/PKC_Manual_Test_Protocol)
- [ ] Create a provisioning script and _skel_ to automatically provision new Playground vps instances
- [ ] Add test to ensure ENV file does not contain spaces Re: https://github.com/inblockio/micro-PKC/issues/81
- [ ] https://github.com/inblockio/micro-PKC/issues/55
- [ ] Harden around MW login, Eauth, Nginx or other entry points
- [ ] Normalize build tooling between repos
  - [ ] Add Makefile to build and publish project in `docker-aqua-mediawiki` (model from mw-docker)
- [ ] Establish Test Matrix. Document support levels for interpreted code (e.g. PHP >= 8.x, Node >= 12.x).

Scrub repos for additional issues.

**Comment by FantasticoFox** [comment]
I propose to postpone https://github.com/inblockio/micro-PKC/issues/57 until 1.4

**Comment by 0xc0000007b** [comment]
Added the following non-trivial item:

- Secure hard-coded database authentication details in build manifest

@rht @FantasticoFox fyi

**Comment by 0xc0000007b** [comment]
Added a few more pertinent items to the hardening list above. The list is large enough now we should revisit it as a team to discuss resource allocation and schedule risk. /cc @FantasticoFox

**Comment by FantasticoFox** [comment]
Lets do so on 29th @0xc0000007b

**Comment by FantasticoFox** [comment]
Related but maybe let's put that for later. https://github.com/inblockio/micro-PKC/issues/90

**Comment by FantasticoFox** [comment]
This is continues work to harden our core. Not part of the prototype release schedule.

**Comment by FantasticoFox** [comment]
@vhs-dev please advice what we should do with this?

**Comment by vhs-dev** [comment]
Closed. Let's continue to iterate on tasks in priority order. Thanks for letting me hijack this issue for planning purpose prior to the [PKC 1.0 Release](https://pkc.inblock.io/index.php/PKC_Version_1.0_Release)
